export interface EndpointDef {
  path: string
  description?: string
  method: string
  auth?: boolean
  idempotent?: boolean
  cache?: boolean
  pager?: boolean
  [key: string]: unknown
}

export interface ApiJson {
  endpoints: Record<string, Record<string, EndpointDef>>
}

function toComment(text?: string): string {
  if (!text) return ''
  return `/**\n * ${text.replace(/\*\//g, '*\\/')}\n */\n`
}

function pathParams(path: string): string[] {
  const fromBraces = [...path.matchAll(/\{(\w+)\}/g)].map(m => m[1]!)
  if (fromBraces.length) return fromBraces
  return [...path.matchAll(/:(\w+)/g)].map(m => m[1]!)
}

function pathTemplate(path: string, names: string[]): string {
  if (!names.length) return `'${path}'`
  let out = path
  for (const name of names) {
    out = out.replaceAll(`{${name}}`, `\${${name}}`)
    out = out.replaceAll(`:${name}`, `\${${name}}`)
  }
  return `\`${out}\``
}

function callOptions(ep: EndpointDef): string {
  const parts: string[] = []
  if (ep.idempotent) parts.push('idempotent: true')
  if (ep.cache && !ep.idempotent) parts.push('cache: true')
  if (ep.auth === false) parts.push('meta: { auth: false }')
  else if (ep.auth === true) parts.push('meta: { auth: true }')
  return parts.join(', ')
}

function mergeOptions(fixed: string, extraExpr: string): string {
  if (!fixed) return extraExpr
  return `{ ${fixed}, ...${extraExpr} }`
}

function genFunction(name: string, ep: EndpointDef): string {
  const method = (ep.method || 'GET').toUpperCase()
  const names = pathParams(ep.path)
  const url = pathTemplate(ep.path, names)
  const fixed = callOptions(ep)
  const pathSig = names.map(n => `${n}: string`).join(', ')
  const http = method === 'DELETE' ? 'delete' : method.toLowerCase()
  const isBodyMethod = !['GET', 'DELETE', 'HEAD', 'OPTIONS'].includes(method)

  let paramsSig: string
  let call: string

  if (ep.pager) {
    const head = [pathSig, 'page: number, size: number', 'options?: FlyreqCallOptions'].filter(Boolean).join(', ')
    paramsSig = head
    const opts = mergeOptions(
      ['params: { page, size }', fixed].filter(Boolean).join(', '),
      'options',
    )
    call = `flyreq.${http}(${url}, ${opts})`
  }
  else if (isBodyMethod) {
    const head = [pathSig, 'data?: unknown', 'options?: FlyreqCallOptions'].filter(Boolean).join(', ')
    paramsSig = head
    const opts = mergeOptions(fixed, 'options')
    call = `flyreq.${http}(${url}, data, ${opts})`
  }
  else if (names.length) {
    paramsSig = `${pathSig}, options?: FlyreqCallOptions`
    const opts = mergeOptions(fixed, 'options')
    call = `flyreq.${http}(${url}, ${opts})`
  }
  else {
    paramsSig = 'params?: Record<string, unknown>, options?: FlyreqCallOptions'
    const opts = mergeOptions(
      ['params', fixed].filter(Boolean).join(', '),
      'options',
    )
    call = `flyreq.${http}(${url}, ${opts})`
  }

  return `${toComment(ep.description)}export async function ${name}(${paramsSig}) {
  return ${call}
}
`
}

export function generateResourceFile(_resourceName: string, endpoints: Record<string, EndpointDef>): string {
  const lines: string[] = [
    `/* Generated by flyreq CLI — do not edit; put customizations in overrides/ */`,
    `import { flyreq, type FlyreqCallOptions } from 'flyreq'`,
    '',
  ]

  for (const [name, ep] of Object.entries(endpoints)) {
    lines.push(genFunction(name, ep))
  }

  return `${lines.join('\n')}\n`
}

export function generateIndexFile(resources: string[]): string {
  return `${resources.map(r => `export * from './${r}'`).join('\n')}\n`
}

export function generateFromApiJson(api: ApiJson): Record<string, string> {
  const files: Record<string, string> = {}
  const resources: string[] = []
  for (const [resource, endpoints] of Object.entries(api.endpoints ?? {})) {
    files[`${resource}.ts`] = generateResourceFile(resource, endpoints)
    resources.push(resource)
  }
  if (resources.length) files['index.ts'] = generateIndexFile(resources)
  return files
}
