export interface EndpointDef {
  path: string
  description?: string
  method: string
  auth?: boolean
  idempotent?: boolean
  cache?: boolean
  pager?: boolean
  [key: string]: unknown
}

export interface ApiJson {
  endpoints: Record<string, Record<string, EndpointDef>>
}

function toComment(text?: string): string {
  if (!text) return ''
  return `/**\n * ${text.replace(/\*\//g, '*\\/')}\n */\n`
}

function pickRequestor(ep: EndpointDef): string {
  if (ep.idempotent) return 'createIdempotentRequestor()'
  if (ep.cache) return 'createCacheRequestor()'
  return 'useRequestor()'
}

function needsCoreImport(endpoints: Record<string, EndpointDef>): {
  idempotent: boolean
  cache: boolean
  plain: boolean
} {
  let idempotent = false
  let cache = false
  let plain = false
  for (const ep of Object.values(endpoints)) {
    if (ep.idempotent) idempotent = true
    else if (ep.cache) cache = true
    else plain = true
  }
  return { idempotent, cache, plain }
}

function genFunction(name: string, ep: EndpointDef): string {
  const method = (ep.method || 'GET').toUpperCase()
  const authMeta = ep.auth === false ? 'false' : ep.auth === true ? 'true' : undefined
  const metaPart = authMeta != null ? `meta: { auth: ${authMeta} }` : ''

  const isBodyMethod = !['GET', 'DELETE', 'HEAD'].includes(method)
  const requestorExpr = pickRequestor(ep)

  let paramsSig: string
  let callArgs: string

  if (ep.pager) {
    paramsSig = 'page: number, size: number'
    const opts = [
      'params: { page, size }',
      metaPart,
    ].filter(Boolean).join(', ')
    callArgs = `undefined, { ${opts} }`
  }
  else if (isBodyMethod) {
    paramsSig = 'data?: unknown'
    const opts = metaPart ? `{ ${metaPart} }` : 'undefined'
    callArgs = `data, ${opts}`
  }
  else {
    paramsSig = 'params?: Record<string, unknown>'
    const opts = [
      'params',
      metaPart,
    ].filter(Boolean)
    // params is already an object variable — spread into options
    if (metaPart) {
      callArgs = `undefined, { params, ${metaPart} }`
    }
    else {
      callArgs = `undefined, { params }`
    }
    void opts
  }

  return `${toComment(ep.description)}export const ${name} = (() => {
  return async (${paramsSig}) => {
    const req = ${requestorExpr}
    return busCall(req, '${method}', '${ep.path}', ${callArgs})
  }
})()
`
}

export function generateResourceFile(resourceName: string, endpoints: Record<string, EndpointDef>): string {
  const flags = needsCoreImport(endpoints)
  const imports: string[] = ['busCall']
  if (flags.idempotent) imports.push('createIdempotentRequestor')
  if (flags.cache) imports.push('createCacheRequestor')
  if (flags.plain) imports.push('useRequestor')

  const lines: string[] = [
    `/* Generated by flyreq CLI — do not edit; put customizations in overrides/ */`,
    `import { ${imports.join(', ')} } from 'flyreq'`,
    '',
  ]

  for (const [name, ep] of Object.entries(endpoints)) {
    lines.push(genFunction(name, ep))
  }

  return `${lines.join('\n')}\n`
}

export function generateFromApiJson(api: ApiJson): Record<string, string> {
  const files: Record<string, string> = {}
  for (const [resource, endpoints] of Object.entries(api.endpoints ?? {})) {
    files[`${resource}.ts`] = generateResourceFile(resource, endpoints)
  }
  return files
}
