// Core
export {
  injectRequestor,
  getRequestor,
  resetRequestor,
  createHttpResponse,
  buildConfig,
  defineRequestor,
  wrapRequestor,
  createEventfulRequestor,
  createMemoryStore,
  createStorageStore,
  createIndexedDBStore,
  createServiceWorkerStore,
  createWebSQLStore,
  createCookieStore,
  createCacheStore,
  resolveCacheStore,
  createCacheRequestor,
  hashRequest,
  createIdempotentRequestor,
  createRetryRequestor,
  createParallelRequestor,
  createSerialRequestor,
  type HttpMethod,
  type RequestConfig,
  type RequestOptions,
  type PlainResponse,
  type HttpResponse,
  type Requestor,
  type RequestEvent,
  type EventfulRequestor,
  type CacheStore,
  type CacheStoreKind,
  type CacheRequestorOptions,
  type IdempotentRequestorOptions,
  type RetryRequestorOptions,
  type ParallelRequestorOptions,
  type SerialRequestorOptions,
} from '@flyreq/core'

// Bus protocol (no auto-inject)
export {
  BusError,
  unwrapEnvelope,
  isApiEnvelope,
  configureBus,
  setRequestToken,
  getRequestToken,
  getBusConfig,
  attachBus,
  injectBus,
  bootstrapRequestor,
  busCall,
  busRequest,
  flyreq,
  configureFlyreq,
  resetFlyreqClient,
  publishArticle,
  getArticles,
  getArticleById,
  type ApiEnvelope,
  type BusConfig,
  type BusCallOptions,
  type FlyreqCallOptions,
  type FlyreqDefaults,
  type FlyreqRetry,
  type FlyreqCache,
  type FlyreqIdempotent,
  type Article,
} from '@flyreq/bus'

// Adapters / transport switching
export {
  setupFlyreq,
  setBackend,
  registerAdapter,
  listBackends,
  getBackend,
  createBackend,
  type SetupFlyreqOptions,
  type BackendName,
} from './setup'

// Low-level creators (advanced)
export { createAxiosRequestor, requestor as axiosRequestor } from '@flyreq/axios'
export { createFetchRequestor, requestor as fetchRequestor } from '@flyreq/fetch'
export { createXhrRequestor, requestor as xhrRequestor } from '@flyreq/xhr'
